//! Repository layer for `file_upload` — the registry of files a user
//! has uploaded through the console, and what became of each one.
//!
//! The file's BYTES are not here: they live in the warehouse bucket under
//! an `uploads/` prefix, and [`Upload::storage_key`] points at them. See
//! `migrations/0049_upload.sql`'s header for why, and for why
//! `storage_key` is always a server-generated name rather than the user's
//! own filename.
//!
//! # Lifecycle
//!
//! `uploaded` -> `ingesting` -> `ingested` | `failed`. Each transition is
//! an UPDATE of the same row (unlike [`crate::audit`], which appends):
//! this table answers "what is the current state of this file", and the
//! durable record of who did what and when is the audit trail's job.

use serde::Serialize;
use serde_json::Value;
use sqlx::FromRow;
use sqlx::types::Json;
use time::OffsetDateTime;

use crate::{PgPool, StoreError};

fn ser_ts<S: serde::Serializer>(at: &OffsetDateTime, s: S) -> Result<S::Ok, S::Error> {
    let at = at.to_offset(time::UtcOffset::UTC);
    s.serialize_str(&format!(
        "{:04}-{:02}-{:02}T{:02}:{:02}:{:02}Z",
        at.year(),
        u8::from(at.month()),
        at.day(),
        at.hour(),
        at.minute(),
        at.second()
    ))
}

#[allow(
    clippy::ref_option,
    reason = "serde's `serialize_with` hands the field by reference; an               `Option<&T>` signature does not match what it calls"
)]
fn ser_ts_opt<S: serde::Serializer>(at: &Option<OffsetDateTime>, s: S) -> Result<S::Ok, S::Error> {
    match at {
        Some(at) => ser_ts(at, s),
        None => s.serialize_none(),
    }
}

/// One uploaded file, as the console lists and inspects it.
#[derive(Debug, Clone, FromRow, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Upload {
    /// Opaque upload id, generated by the API.
    pub id: String,
    /// The browser-reported name, for display only — never a storage path.
    pub original_filename: String,
    /// Object key in the warehouse bucket (`uploads/<tenant>/<id>.<ext>`).
    pub storage_key: String,
    /// MIME type the browser claimed. Advisory only — an export named
    /// `.xls` is routinely UTF-16 TSV, so detection wins over this.
    pub content_type: String,
    /// Size of the stored object, in bytes.
    pub size_bytes: i64,
    /// Hex SHA-256 of the stored bytes, for duplicate detection.
    pub sha256: String,
    /// Display name of the principal who uploaded it.
    pub uploaded_by: String,
    /// Tenant the upload belongs to; also its storage-key prefix.
    pub tenant: String,
    /// `uploaded` | `ingesting` | `ingested` | `failed`.
    pub status: String,
    /// What an ingest was told to use (encoding, delimiter, header row).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parse_options: Option<Json<Value>>,
    /// Bronze table this file became, once ingested.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bronze_table: Option<String>,
    /// Dagster run id of the ingest, for linking to its logs.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub run_id: Option<String>,
    /// Failure reason when `status` is `failed`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// When the bytes were stored.
    #[serde(serialize_with = "ser_ts")]
    pub created_at: OffsetDateTime,
    /// When the row last changed state.
    #[serde(serialize_with = "ser_ts_opt")]
    pub updated_at: Option<OffsetDateTime>,
}

const COLS: &str = "id, original_filename, storage_key, content_type, size_bytes, sha256, \
                    uploaded_by, tenant, status, parse_options, bronze_table, run_id, error, \
                    created_at, updated_at";

/// Everything needed to record a file whose bytes are already stored.
///
/// Deliberately taken AFTER the upload to object storage succeeds: a row
/// here means "these bytes exist at this key". Writing the row first would
/// leave a registry entry pointing at nothing whenever the store write
/// failed, and every consumer would have to treat every row as maybe-real.
#[derive(Debug, Clone)]
pub struct NewUpload<'a> {
    /// Upload id, generated by the caller before the object is stored.
    pub id: &'a str,
    /// Browser-reported filename, for display only.
    pub original_filename: &'a str,
    /// Object key the bytes were written to.
    pub storage_key: &'a str,
    /// Browser-reported MIME type; advisory (see [`Upload::content_type`]).
    pub content_type: &'a str,
    /// Size of the stored object, in bytes.
    pub size_bytes: i64,
    /// Hex SHA-256 of the stored bytes.
    pub sha256: &'a str,
    /// Display name of the uploading principal.
    pub uploaded_by: &'a str,
    /// Tenant the upload belongs to.
    pub tenant: &'a str,
}

/// Record an uploaded file.
///
/// # Errors
///
/// Returns [`StoreError`] on a database failure, including the unique
/// violation raised when `storage_key` is already registered.
pub async fn insert(pool: &PgPool, new: &NewUpload<'_>) -> Result<Upload, StoreError> {
    let sql = format!(
        "INSERT INTO file_upload \
         (id, original_filename, storage_key, content_type, size_bytes, sha256, uploaded_by, tenant) \
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING {COLS}"
    );
    Ok(sqlx::query_as(&sql)
        .bind(new.id)
        .bind(new.original_filename)
        .bind(new.storage_key)
        .bind(new.content_type)
        .bind(new.size_bytes)
        .bind(new.sha256)
        .bind(new.uploaded_by)
        .bind(new.tenant)
        .fetch_one(pool)
        .await?)
}

/// Newest-first listing, optionally scoped to one tenant.
///
/// # Errors
///
/// Returns [`StoreError`] on a database failure.
pub async fn list(
    pool: &PgPool,
    tenant: Option<&str>,
    limit: i64,
) -> Result<Vec<Upload>, StoreError> {
    let limit = limit.clamp(1, 500);
    let sql = format!(
        "SELECT {COLS} FROM file_upload \
         WHERE ($1::text IS NULL OR tenant = $1) \
         ORDER BY created_at DESC LIMIT {limit}"
    );
    Ok(sqlx::query_as(&sql).bind(tenant).fetch_all(pool).await?)
}

/// One upload by id, or `None`.
///
/// # Errors
///
/// Returns [`StoreError`] on a database failure.
pub async fn get(pool: &PgPool, id: &str) -> Result<Option<Upload>, StoreError> {
    let sql = format!("SELECT {COLS} FROM file_upload WHERE id = $1");
    Ok(sqlx::query_as(&sql).bind(id).fetch_optional(pool).await?)
}

/// The most recent upload carrying `sha256`, excluding `exclude_id`.
///
/// Used to tell a user they are uploading a file the system already holds,
/// BEFORE its rows are appended to Bronze a second time.
///
/// # Errors
///
/// Returns [`StoreError`] on a database failure.
pub async fn find_by_sha256(
    pool: &PgPool,
    sha256: &str,
    exclude_id: &str,
) -> Result<Option<Upload>, StoreError> {
    let sql = format!(
        "SELECT {COLS} FROM file_upload \
         WHERE sha256 = $1 AND sha256 <> '' AND id <> $2 \
         ORDER BY created_at DESC LIMIT 1"
    );
    Ok(sqlx::query_as(&sql)
        .bind(sha256)
        .bind(exclude_id)
        .fetch_optional(pool)
        .await?)
}

/// Move an upload to `ingesting`, recording the options the ingest was
/// given and the Dagster run carrying it out.
///
/// # Errors
///
/// Returns [`StoreError`] on a database failure.
pub async fn mark_ingesting(
    pool: &PgPool,
    id: &str,
    parse_options: &Value,
    bronze_table: &str,
    run_id: Option<&str>,
) -> Result<Option<Upload>, StoreError> {
    let sql = format!(
        "UPDATE file_upload SET status = 'ingesting', parse_options = $2, \
         bronze_table = $3, run_id = $4, error = NULL, updated_at = now() \
         WHERE id = $1 RETURNING {COLS}"
    );
    Ok(sqlx::query_as(&sql)
        .bind(id)
        .bind(Json(parse_options.clone()))
        .bind(bronze_table)
        .bind(run_id)
        .fetch_optional(pool)
        .await?)
}

/// Terminal state: `ingested` when `error` is `None`, `failed` otherwise.
///
/// # Errors
///
/// Returns [`StoreError`] on a database failure.
pub async fn mark_finished(
    pool: &PgPool,
    id: &str,
    error: Option<&str>,
) -> Result<Option<Upload>, StoreError> {
    let sql = format!(
        "UPDATE file_upload \
         SET status = CASE WHEN $2::text IS NULL THEN 'ingested' ELSE 'failed' END, \
             error = $2, updated_at = now() \
         WHERE id = $1 RETURNING {COLS}"
    );
    Ok(sqlx::query_as(&sql)
        .bind(id)
        .bind(error)
        .fetch_optional(pool)
        .await?)
}

/// Remove an upload's registry row. The caller deletes its object first —
/// a row without bytes is a broken link, bytes without a row are an orphan
/// only a storage sweep can find.
///
/// # Errors
///
/// Returns [`StoreError`] on a database failure.
pub async fn delete(pool: &PgPool, id: &str) -> Result<bool, StoreError> {
    let done = sqlx::query("DELETE FROM file_upload WHERE id = $1")
        .bind(id)
        .execute(pool)
        .await?;
    Ok(done.rows_affected() > 0)
}
