-- Phase 2, Task 2.6: demo/seed alert instances, from `mock/overview.ts`'s
-- `buildAlerts`. Fixed ids + `ON CONFLICT DO NOTHING` make this idempotent.
INSERT INTO alert_instance (id, title, severity, source, affected, status, assignee, at, detail, resolution_note, href, created_at)
VALUES
    ('al-01', 'Streaming lag above threshold',        'high',     'Real-time plane',    'rt.orders_flow_mv',           'open',         'On-call data platform', now() - interval '12 minutes',  'Barrier latency exceeded 30 s for 3 consecutive intervals. Sink to hot store is delayed; downstream freshness on revenue dashboards is degraded.', NULL, '/streaming/sj-orders-flow',        now() - interval '1 second'),
    ('al-02', 'Pipeline failed after retries',         'critical', 'Ingestion plane',    'erp_inventory_sync',          'acknowledged', 'Bayu Pratama',           now() - interval '48 minutes',  'Source API returned schema-mismatch errors on 3 retries. Dead-letter target captured 1,204 records. Manual mapping review required.',              NULL, '/pipelines/pl-erp-inventory',      now() - interval '2 seconds'),
    ('al-03', 'Residency policy blocked a query',      'medium',   'Access layer',       'tenant: meridian-group',      'open',         NULL,                     now() - interval '95 minutes',  'A federated query attempted to move restricted rows out of the approved on-premise site. The plan was rejected with an explicit policy error.',    NULL, '/residency',                       now() - interval '3 seconds'),
    ('al-04', 'Agent budget nearing limit',            'low',      'Agent operations',   'inventory-copilot',           'open',         NULL,                     now() - interval '130 minutes', 'Monthly compute budget at 82%. Reservations will start failing at 100%; consider raising the budget or lowering run frequency.',                    NULL, '/agents/employees/emp-inventory',  now() - interval '4 seconds'),
    ('al-05', 'Quality check failing on curated table','medium',   'Data quality',       'serving.mart_customer_segment','resolved',    'Dewi Anggraini',         now() - interval '300 minutes', 'Completeness on email_verified dropped to 91% after an upstream mapping change. Fixed by re-running the enrichment step.',                          'Enrichment step re-run; completeness back to 99.2%.', '/governance/data-quality', now() - interval '5 seconds')
ON CONFLICT DO NOTHING;
