-- Phase 2, Task 2.7: demo/seed connector definitions.
--
-- The fixtures from `src/services/mock/connectors.ts`, so the Connectors
-- screen isn't empty the moment `mockConnectorService` stops being
-- reachable -- same convention as `0008_seed_pipelines.sql`. `secret_ref`
-- values below are REFERENCE NAMES only (`env:*` / `vault:*`), never
-- credential material -- see `0013_connectors.sql`'s header comment; there
-- is no `EXAMPLE_PASSWORD=...` anywhere in this file or anywhere else in
-- this repository, by design. Fixed ids + `ON CONFLICT DO NOTHING` (matched
-- via the primary key) make this idempotent.
INSERT INTO connector (id, name, type, direction, health, environment, tenant, host, secret_ref, residency, last_test_at, last_activity_at, capabilities, owner, created_at)
VALUES
    ('conn-pg-oms', 'order management system (CDC)', 'PostgreSQL CDC', 'source', 'healthy', 'production', 'Meridian Group', 'oms-db.internal:5432', 'env:PG_OMS_CDC_PASSWORD', 'in-region', now() - interval '45 minutes', now() - interval '1 minutes', ARRAY['CDC','schema discovery','checkpoint','backfill'], 'Commerce Platform Team', now()),
    ('conn-mysql-pos', 'retail store POS (legacy)', 'MySQL CDC', 'source', 'degraded', 'production', 'Meridian Group', 'pos-legacy-db.internal:3306', 'env:MYSQL_POS_PASSWORD', 'in-region', now() - interval '20 minutes', now() - interval '6 minutes', ARRAY['CDC','schema discovery'], 'Retail Systems', now()),
    ('conn-mongo-catalog', 'product catalog service', 'MongoDB', 'source', 'healthy', 'production', 'Meridian Group', 'catalog-mongo.internal:27017', 'env:MONGO_CATALOG_URI', 'in-region', now() - interval '180 minutes', now() - interval '30 minutes', ARRAY['change streams','schema inference'], 'Merchandising', now()),
    ('conn-api-marketplace', 'marketplace partner API', 'REST API', 'source', 'healthy', 'production', 'Meridian Group', 'api.marketplace-partner.example', 'vault:secret/data/connectors/marketplace-api', 'in-region', now() - interval '90 minutes', now() - interval '12 minutes', ARRAY['paginated pull','rate limit aware','incremental cursor'], 'Commerce Platform Team', now()),
    ('conn-crm-cloud', 'CRM customer master', 'CRM API', 'bidirectional', 'healthy', 'production', 'Meridian Group', 'crm.vendor.example', 'vault:secret/data/connectors/crm-cloud', 'in-region', now() - interval '240 minutes', now() - interval '55 minutes', ARRAY['bulk export','upsert writeback','field mapping'], 'CRM Team', now()),
    ('conn-kafka-orders', 'order events stream', 'Kafka', 'bidirectional', 'healthy', 'production', 'Meridian Group', 'kafka-broker.internal:9092', 'env:KAFKA_ORDERS_SASL', 'in-region', now() - interval '15 minutes', now() - interval '0 minutes', ARRAY['consume','produce','pushdown filters','exactly-once'], 'Streaming Platform', now()),
    ('conn-kafka-clickstream', 'web & app clickstream', 'Kafka', 'source', 'healthy', 'production', 'Meridian Group', 'kafka-broker.internal:9092', 'env:KAFKA_CLICKSTREAM_SASL', 'in-region', now() - interval '15 minutes', now() - interval '0 minutes', ARRAY['consume','schema registry','pushdown filters'], 'Digital Analytics', now()),
    ('conn-kafka-fleet', 'fleet telematics stream', 'Kafka', 'source', 'degraded', 'production', 'Meridian Group', 'kafka-broker.internal:9092', 'env:KAFKA_FLEET_SASL', 'in-region', now() - interval '8 minutes', now() - interval '0 minutes', ARRAY['consume','schema registry'], 'Fleet Telematics', now()),
    ('conn-mqtt-warehouse', 'warehouse IoT broker', 'MQTT', 'source', 'healthy', 'production', 'Meridian Group', 'mqtt-broker.internal:8883', 'env:MQTT_WAREHOUSE_PASSWORD', 'in-region', now() - interval '25 minutes', now() - interval '0 minutes', ARRAY['subscribe','QoS 1','device registry sync'], 'Warehouse Automation', now()),
    ('conn-s3-landing', 'raw landing bucket', 'Object storage', 'source', 'healthy', 'production', 'Meridian Group', 's3://meridian-landing', 'vault:secret/data/connectors/s3-landing', 'in-region', now() - interval '60 minutes', now() - interval '18 minutes', ARRAY['list','read','event notify','parquet'], 'Data Platform', now()),
    ('conn-sftp-bank', 'bank statement drop (SFTP)', 'SFTP', 'source', 'healthy', 'production', 'Meridian Group', 'sftp.bank-partner.example:22', 'vault:secret/data/connectors/sftp-bank', 'in-region', now() - interval '720 minutes', now() - interval '300 minutes', ARRAY['scheduled pull','PGP decrypt','checksum verify'], 'Finance Systems', now()),
    ('conn-gsheets-ops', 'ops planning spreadsheets', 'Google Sheets', 'source', 'unhealthy', 'staging', 'Meridian Group', 'sheets.googleapis.com', 'env:GSHEETS_OAUTH_REFRESH_TOKEN', 'in-region', now() - interval '2880 minutes', now() - interval '4320 minutes', ARRAY['range read','header inference'], 'Supply Chain Ops', now()),
    ('conn-erp-finance', 'ERP financial ledger', 'SAP / ERP', 'source', 'healthy', 'production', 'Meridian Group', 'erp.internal:3300', 'env:ERP_FINANCE_PASSWORD', 'in-region', now() - interval '300 minutes', now() - interval '120 minutes', ARRAY['table extract','delta by timestamp'], 'Finance Systems', now()),
    ('conn-oracle-gl', 'general ledger (Oracle)', 'Oracle', 'source', 'healthy', 'production', 'Meridian Group', 'oracle-gl.internal:1521', 'env:ORACLE_GL_PASSWORD', 'in-region', now() - interval '300 minutes', now() - interval '180 minutes', ARRAY['JDBC extract','partitioned read'], 'Finance Systems', now()),
    ('conn-payment-gateway', 'payment gateway API', 'REST API', 'source', 'healthy', 'production', 'Meridian Group', 'api.payment-gateway.example', 'vault:secret/data/connectors/payment-gateway', 'in-region', now() - interval '35 minutes', now() - interval '4 minutes', ARRAY['incremental cursor','webhook ingest','retry with backoff'], 'Payments Platform', now()),
    ('conn-ads-platform', 'ad platform spend API', 'Ads API', 'source', 'healthy', 'production', 'Meridian Group', 'api.ads-platform.example', 'vault:secret/data/connectors/ads-platform', 'in-region', now() - interval '100 minutes', now() - interval '22 minutes', ARRAY['report pull','attribution window','currency normalize'], 'Growth Marketing', now()),
    ('conn-web-analytics', 'web analytics export', 'Analytics API', 'source', 'healthy', 'production', 'Meridian Group', 'api.web-analytics.example', 'vault:secret/data/connectors/web-analytics', 'in-region', now() - interval '140 minutes', now() - interval '26 minutes', ARRAY['report pull','sampling control'], 'Digital Analytics', now()),
    ('conn-esp-email', 'email service provider', 'Marketing API', 'bidirectional', 'healthy', 'production', 'Meridian Group', 'api.esp-vendor.example', 'vault:secret/data/connectors/esp-email', 'in-region', now() - interval '200 minutes', now() - interval '48 minutes', ARRAY['campaign metrics','audience writeback'], 'Growth Marketing', now()),
    ('conn-hris', 'HRIS employee directory', 'HRIS API', 'source', 'healthy', 'production', 'Meridian Group', 'api.hris-vendor.example', 'vault:secret/data/connectors/hris', 'in-region', now() - interval '600 minutes', now() - interval '540 minutes', ARRAY['scheduled pull','PII masking at source'], 'People Operations', now()),
    ('conn-fx-rates', 'FX rate provider', 'REST API', 'source', 'healthy', 'production', 'Meridian Group', 'api.fx-rates.example', 'env:FX_RATES_API_KEY', 'in-region', now() - interval '70 minutes', now() - interval '60 minutes', ARRAY['daily pull','multi-provider fallback'], 'Finance Systems', now()),
    ('conn-weather', 'weather observation API', 'REST API', 'source', 'healthy', 'production', 'Meridian Group', 'api.weather.example', 'env:WEATHER_API_KEY', 'in-region', now() - interval '70 minutes', now() - interval '58 minutes', ARRAY['daily pull','geo lookup'], 'Data Science', now()),
    ('conn-market-data', 'commodity & freight index', 'Market data feed', 'source', 'healthy', 'production', 'Meridian Group', 'feed.market-data.example', 'vault:secret/data/connectors/market-data', 'in-region', now() - interval '160 minutes', now() - interval '150 minutes', ARRAY['licensed feed','daily settle prices'], 'Procurement', now()),
    ('conn-price-crawler', 'competitor price crawler', 'Web crawler', 'source', 'degraded', 'production', 'Meridian Group', 'crawler-worker.internal', 'env:PRICE_CRAWLER_PROXY_TOKEN', 'in-region', now() - interval '50 minutes', now() - interval '14 minutes', ARRAY['scheduled crawl','SKU matching','robots respect'], 'Pricing Strategy', now()),
    ('conn-social-listening', 'social listening vendor', 'Vendor API', 'source', 'healthy', 'production', 'Meridian Group', 'api.social-listening.example', 'vault:secret/data/connectors/social-listening', 'in-region', now() - interval '40 minutes', now() - interval '2 minutes', ARRAY['streaming firehose','sentiment scoring','language detect'], 'Brand & Comms', now()),
    ('conn-credit-bureau', 'credit bureau scores', 'Vendor API', 'source', 'healthy', 'production', 'Meridian Group', 'api.credit-bureau.example', 'vault:secret/data/connectors/credit-bureau', 'in-region', now() - interval '1400 minutes', now() - interval '1380 minutes', ARRAY['monthly batch','consent tracking','PII encryption'], 'Credit Risk', now()),
    ('conn-iceberg-catalog', 'Iceberg REST catalog', 'Iceberg catalog', 'bidirectional', 'healthy', 'production', 'Meridian Group', 'iceberg-catalog.internal:8181', 'env:ICEBERG_CATALOG_TOKEN', 'in-region', now() - interval '10 minutes', now() - interval '1 minutes', ARRAY['table create','snapshot expire','compaction'], 'Data Platform', now()),
    ('conn-clickhouse-serving', 'ClickHouse serving layer', 'ClickHouse', 'sink', 'healthy', 'production', 'Meridian Group', 'clickhouse.internal:8443', 'env:CLICKHOUSE_SERVING_PASSWORD', 'in-region', now() - interval '5 minutes', now() - interval '0 minutes', ARRAY['bulk insert','async insert','TTL policy'], 'Data Platform', now()),
    ('conn-partner-share', 'partner data share (outbound)', 'Data share', 'sink', 'healthy', 'production', 'Meridian Group', 'share.partner.example', 'vault:secret/data/connectors/partner-share', 'in-region', now() - interval '480 minutes', now() - interval '400 minutes', ARRAY['scoped share','row filter','revocable grant'], 'Data Governance', now())
ON CONFLICT DO NOTHING;
