/**
 * Files a user uploads from the console, and the load of each one into a raw
 * table. Mirrors the routes under `/api/uploads`
 * (`rust/crates/lakehouse-api/src/routes/uploads.rs`), plan T10 of
 * `docs/superpowers/plans/2026-10-02-upload-file.md`, decisions in ADR 0014.
 *
 * Every error the API answers is `{ "error": "<sentence>" }` and the sentence
 * is written for the person reading it; the client carries it into a
 * `ServiceError` unchanged and the screens show it as it is.
 */

/**
 * `uploaded` (stored, never loaded), `ingesting` (a load is running),
 * `ingested` (loaded) or `failed`. Widened with `| string` because the Rust
 * field is a plain `String` (`lakehouse_store::uploads::Upload::status`), so
 * the client stays honest about a value a later version might add.
 */
export type UploadStatus = "uploaded" | "ingesting" | "ingested" | "failed" | string

/**
 * What a load does with the rows a table already holds: `replace` swaps them
 * for the file's, `append` adds the file's after them. Mirrors Rust
 * `LoadMode` in `lakehouse-store/src/uploads.rs` (an upload has these two;
 * a connector's `incremental` does not apply to a file).
 */
export type UploadLoadMode = "replace" | "append"

/** The two encodings a delimited text file may be read as. */
export type UploadEncoding = "utf-8" | "utf-16"

/**
 * How a file is read: the three settings a load is told. Mirrors Rust
 * `Reading` (`lakehouse-api/src/upload_parse.rs`) field for field.
 *
 * - `delimiter` is one character, and a tab is the tab character itself
 *   (`"\t"`), never the two characters `\` and `t`.
 * - `headerRow` is the ZERO-BASED index of the record that holds the column
 *   names, counting every record the file has above the data (report lines
 *   and blank ones included). The screens show it from 1; the conversion
 *   lives in `@/lib/uploads` (`headerRowDisplay`, `headerRowFromDisplay`) and
 *   nowhere else.
 */
export type UploadParseOptions = {
  encoding: UploadEncoding
  delimiter: string
  headerRow: number
  /**
   * For an Excel workbook: the sheet read. Sent to the preview and the load
   * to choose a sheet, and recorded by the API on a workbook's load (so a
   * retry sends it back). Never set for a text file. A workbook is always read
   * as UTF-8 with commas, so `encoding` and `delimiter` mean nothing for it.
   */
  sheet?: string
}

/** One sheet of an uploaded workbook. */
export type UploadSheet = {
  name: string
  /** `false` for a hidden sheet; it can still be chosen. */
  visible: boolean
}

/**
 * The sheets of an uploaded Excel workbook (`.xls`, `.xlsx`), in workbook
 * order. Mirrors Rust `WorkbookInfo` (`lakehouse-api/src/upload_workbook.rs`).
 */
export type UploadWorkbook = {
  sheets: UploadSheet[]
  /** The first visible sheet: the one read when none is chosen. */
  defaultSheet: string
}

/**
 * One uploaded file, as `GET /api/uploads` and `GET /api/uploads/{id}`
 * return it. The API never sends the object key, the tenant, the content
 * type or the checksum (review finding B3); an upload belongs to the
 * caller's tenant and the console only ever sees its own.
 */
export type Upload = {
  /** Opaque id, generated by the API. */
  id: string
  /** The browser-reported name, for display only. */
  originalFilename: string
  sizeBytes: number
  /** Display name of whoever uploaded it. */
  uploadedBy: string
  status: UploadStatus
  /** ISO 8601, UTC. When the bytes were stored. */
  createdAt: string
  /** ISO 8601, UTC. When the row last changed state; for a load, the time it was claimed. */
  updatedAt: string
  /** What the last load was told to use. Absent until a load was requested. */
  parseOptions?: UploadParseOptions
  /** The raw table the last load targeted. */
  bronzeTable?: string
  loadMode?: UploadLoadMode | string
  /**
   * The row count the load reported. ABSENT MEANS NOT MEASURED (still
   * loading, failed, or the writer reported no total), and is never `0`:
   * a screen must read it as "Not measured", not as an empty table.
   */
  rows?: number
  /** The orchestrator run of the last load. */
  runId?: string
  /**
   * Why the last load failed, when `status` is `failed`. One of the API's
   * fixed sentences: a reason `file_ingest_job` records
   * (`ops/fixtures/upload_load_failure_reasons.json`), or one the API wrote
   * itself when a load never started or recorded nothing. Never exception
   * text (review finding B6).
   */
  error?: string
  /**
   * The catalog slug of the loaded table (its name with `_` as `-`), the
   * `<assetId>` of `/data/assets/<assetId>`. Present only when `status` is
   * `ingested`.
   */
  assetId?: string
}

/**
 * `POST /api/uploads`'s response (201): the new upload and, when the caller's
 * tenant already holds the same bytes, the earlier upload as `duplicateOf`.
 * A duplicate is reported and never refused: the same file legitimately
 * arrives twice, and loading it again with `append` doubles its rows.
 */
export type CreateUploadResponse = Upload & {
  duplicateOf?: Upload
  /** Present when the file is an Excel workbook: its sheets. */
  workbook?: UploadWorkbook
}

/**
 * `GET /api/uploads/{id}/preview`: what the first bytes of the file contain.
 * Never the size of the file: a preview does not count what it did not read.
 */
export type UploadPreview = {
  /**
   * What detection found. The delimiter and the header row are detected under
   * the settings in force, because a header guess means nothing under a
   * delimiter the user has just rejected.
   */
  detected: UploadParseOptions
  /** What is in force: the detected value unless the request overrode it. */
  using: UploadParseOptions
  /**
   * The header record's cells, untouched (not the names the table's columns
   * will get). EMPTY when the header row is past what was read, or is an
   * empty line: a screen must say so and not offer to go on.
   */
  columns: string[]
  /** At most 20 records below the header that are not blank, as parsed: a short or long record is not padded or cut. */
  rows: string[][]
  /** The file holds more than `rows` shows. */
  truncated: boolean
  /**
   * Present when the file is an Excel workbook: the sheet this preview shows
   * and the sheets there are. `detected` and `using` then read UTF-8 and a
   * comma, the fixed dialect the API converts a sheet to; only `headerRow`
   * is the person's to choose.
   */
  workbook?: UploadWorkbook & { sheet: string }
}

/**
 * The `POST /api/uploads/{id}/ingest` body. All of it is what the user
 * confirmed: the API loads with exactly these settings and guesses nothing.
 */
export type IngestUploadInput = UploadParseOptions & {
  /** A name the API's table rule accepts (`tableNameProblem` in `@/lib/uploads`). */
  bronzeTable: string
  /** `replace` when absent. */
  mode?: UploadLoadMode
}

/** `POST /api/uploads/{id}/ingest`'s response: the upload, now `ingesting`, and the run carrying the load out. */
export type IngestUploadResponse = {
  upload: Upload
  runId: string
}

export interface UploadService {
  /** `GET /api/uploads`: the active tenant's uploads, newest first, at most 100. A bare array. */
  list(signal?: AbortSignal): Promise<Upload[]>
  /** `GET /api/uploads/{id}`: one upload; a loading one is settled by the API first. 404 outside the tenant. */
  get(id: string, signal?: AbortSignal): Promise<Upload>
  /**
   * `POST /api/uploads`: sends the file as a multipart form with one part
   * named `file`. The API refuses an empty file, one over 50 MB and one that
   * is neither delimited text nor an `.xls` or `.xlsx` workbook that opens,
   * each with its own sentence.
   */
  create(file: File, signal?: AbortSignal): Promise<CreateUploadResponse>
  /**
   * `GET /api/uploads/{id}/preview`. Each option given overrides detection;
   * one left out is detected. `headerRow` is zero-based. `sheet` chooses the
   * sheet of a workbook (its first visible one when left out).
   */
  preview(
    id: string,
    options?: Partial<UploadParseOptions>,
    signal?: AbortSignal
  ): Promise<UploadPreview>
  /** `POST /api/uploads/{id}/ingest`: starts the load. 409 for a table the upload may not load into. */
  ingest(id: string, input: IngestUploadInput, signal?: AbortSignal): Promise<IngestUploadResponse>
  /** `DELETE /api/uploads/{id}` (204): removes the file and its entry. Never the table. 409 while loading. */
  remove(id: string, signal?: AbortSignal): Promise<void>
}
