//! Static "metrics as code" chart and KPI definitions.
//!
//! Ports `src/lib/dashboard-specs.ts` — a thin semantic layer for
//! dashboarding: each card is defined once here (its `ClickHouse` SQL, run
//! server-side, plus how to render it), sourced exclusively from the Gold
//! marts under `serving.*` (the only layer dashboards are allowed to read;
//! Raw/Bronze/Silver are off-limits).

use std::sync::LazyLock;

use serde::{Deserialize, Serialize};

/// How a chart's data should be rendered.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ChartKind {
    /// Vertical bar chart.
    Bar,
    /// Horizontal bar chart.
    Hbar,
    /// Line chart.
    Line,
    /// Area chart.
    Area,
    /// Stacked bar/area chart (multiple `y` series).
    Stacked,
    /// Combined bar + line chart.
    Combo,
    /// Pie chart.
    Pie,
    /// Rose (polar area) chart.
    Rose,
    /// Funnel chart.
    Funnel,
    /// Treemap.
    Treemap,
    /// Scatter plot.
    Scatter,
    /// Bubble chart.
    Bubble,
    /// Heatmap.
    Heatmap,
    /// Radar chart.
    Radar,
    /// Waterfall chart.
    Waterfall,
    /// Geographic choropleth map.
    Geomap,
    /// Single-number KPI tile.
    Kpi,
    /// Single-number gauge tile.
    Gauge,
    /// Raw data table.
    Table,
    /// Free-text markdown tile (no SQL).
    Text,
}

/// Numeric display format for a chart or KPI value.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum NumFmt {
    /// Integer display.
    Int,
    /// Floating-point display.
    Float,
}

/// Aggregate function applied to a chart's measure column(s). Ports the TS
/// `AGGS` set (`bi-store.ts:53`: `sum`/`avg`/`max`/`min`/`count`).
///
/// [`crate::store`]'s module doc claims there is no SQL injection path
/// because chart SQL is assembled only from validated identifiers — but
/// before this type existed, `QueryBuilder::aggregate` took `impl
/// Into<String>` and interpolated it raw into the generated SQL. On the
/// `spec_from_input` path the string was allowlisted first (via
/// `aggregate_allowed`), but on the `sql_with_filters` path it came
/// straight from a stored `spec_json`'s `def.aggregate` and was NEVER
/// re-checked — reachable only by whoever already has direct write access
/// to `console.bi_chart` (not via any HTTP route), but it meant the doc
/// claim wasn't true by construction. This enum makes it true: the only
/// way to get an `Aggregate` out of untrusted text is
/// [`Aggregate::from_str_lossy`], which can only ever produce one of the
/// five known variants — an unrecognized string can never reach the SQL
/// builder as raw text.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Aggregate {
    /// `sum(...)` — also the default when unset or unrecognized.
    #[default]
    Sum,
    /// `avg(...)`.
    Avg,
    /// `max(...)`.
    Max,
    /// `min(...)`.
    Min,
    /// `count()`.
    Count,
}

impl Aggregate {
    /// The lowercase `ClickHouse` function name this aggregate renders as
    /// (`count` renders as `count()`, callers handle that specially).
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Sum => "sum",
            Self::Avg => "avg",
            Self::Max => "max",
            Self::Min => "min",
            Self::Count => "count",
        }
    }

    /// Parse a stored aggregate string, falling back to [`Aggregate::Sum`]
    /// for anything unrecognized (case-insensitively) — matching the TS
    /// `d.aggregate ?? "sum"` default (`bi-store.ts:394`) and, per the
    /// data-loss lesson of B1, extended to cover a genuinely corrupt/unknown
    /// value too: this must NEVER error, since `sql_with_filters` runs
    /// against already-stored rows and an error here would either panic or
    /// have to fall back to dropping the chart, both worse than silently
    /// defaulting to `sum` (the TS's own behavior for a missing aggregate).
    #[must_use]
    pub fn from_str_lossy(s: &str) -> Self {
        match s.to_ascii_lowercase().as_str() {
            "avg" => Self::Avg,
            "max" => Self::Max,
            "min" => Self::Min,
            "count" => Self::Count,
            _ => Self::Sum,
        }
    }
}

impl std::fmt::Display for Aggregate {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Where a chart spec originated: bundled with the app, generated by the AI
/// chat tool, or created manually through the dashboard builder UI.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ChartSource {
    /// Bundled with the app (this module's `KPIS`/`CHARTS` constants).
    Builtin,
    /// Generated by the AI chat tool.
    Ai,
    /// Created manually through the dashboard builder UI.
    Ui,
}

/// A single-number KPI. The `sql` must return a column named `v` (and may
/// return other columns too).
#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct KpiSpec {
    /// Stable identifier.
    pub id: String,
    /// Display title.
    pub title: String,
    /// `ClickHouse` SQL that returns a `v` column.
    pub sql: String,
    /// Numeric display format.
    pub format: NumFmt,
    /// Optional caption/unit shown under the value.
    pub caption: Option<String>,
    /// Source mart — for lineage/labeling.
    pub mart: String,
}

/// A chart's `y` axis: a single measure column, or several for a stacked
/// chart.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ChartY {
    /// A single measure column.
    Single(String),
    /// Multiple measure columns (used by `kind: "stacked"`).
    Multi(Vec<String>),
}

/// A chart. `sql` returns rows; `x`/`y` name the columns used for the
/// axis/series.
#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct ChartSpec {
    /// Stable identifier.
    pub id: String,
    /// Display title.
    pub title: String,
    /// Optional subtitle.
    pub subtitle: Option<String>,
    /// How to render the data.
    pub kind: ChartKind,
    /// Source mart — for lineage/labeling.
    pub mart: String,
    /// `ClickHouse` SQL that returns the chart's rows.
    pub sql: String,
    /// Column name for the X axis / category.
    pub x: String,
    /// Column name(s) for the Y axis / measure(s).
    pub y: ChartY,
    /// Optional 2nd-dimension breakdown column: splits `y` into multiple
    /// series by this column's value. When set, `y` is a single measure and
    /// the data is long-format (x, series, value).
    pub series: Option<String>,
    /// Numeric display format.
    pub format: Option<NumFmt>,
    /// Grid span; `2` = full width.
    pub span: Option<u8>,
    /// Markdown content for `kind: "text"` tiles (no SQL).
    pub text: Option<String>,
    /// Caption/unit for `kind: "kpi"` tiles.
    pub caption: Option<String>,
    /// Target/max value for `kind: "gauge"` tiles (auto from data when
    /// unset).
    pub target: Option<f64>,
}

/// The JSON document `BUILTIN_DASHBOARD_SPEC` points at: the built-in
/// "Main" dashboard's tile catalog, per tenant. An empty/missing file — or
/// an unset `BUILTIN_DASHBOARD_SPEC` — means no built-in tiles at all
/// (`routes::dashboard::get_body` treats an empty `KPIS`/`CHARTS` as
/// "board disabled", replacing the retired `BUILTIN_DASHBOARD_ENABLED`
/// flag).
#[derive(Debug, Clone, Default, Deserialize)]
pub struct BuiltinDashboardSpecFile {
    #[serde(default)]
    kpis: Vec<KpiSpec>,
    #[serde(default)]
    charts: Vec<ChartSpec>,
}

/// Parse a `BUILTIN_DASHBOARD_SPEC` document from its raw text. Exposed
/// (`pub(crate)` would suffice for `dashboard.rs`, but this is `pub` so
/// `tests/specs_match_typescript.rs` — an external integration test — can
/// call it directly on the shipped default file rather than relying on the
/// process-wide `KPIS`/`CHARTS` statics, which would require setting
/// `BUILTIN_DASHBOARD_SPEC` via `std::env::set_var` in a test binary shared
/// with other tests (AGENTS.md: never do that).
///
/// # Errors
///
/// Returns a [`serde_json::Error`] if `raw` is not valid JSON matching this
/// shape. Malformed JSON is the caller's decision to treat as "disabled"
/// ([`load_builtin_dashboard_spec`] does exactly that); this function
/// itself reports the real error rather than swallowing it, so a test (like
/// the ones below) can assert on the failure directly.
pub fn parse_builtin_dashboard_spec(
    raw: &str,
) -> Result<BuiltinDashboardSpecFile, serde_json::Error> {
    serde_json::from_str(raw)
}

impl BuiltinDashboardSpecFile {
    /// Public accessors so external callers of
    /// [`parse_builtin_dashboard_spec`] (the parity test) can read the
    /// parsed fields without this struct's fields themselves needing to be
    /// `pub`.
    #[must_use]
    pub fn kpis(&self) -> &[KpiSpec] {
        &self.kpis
    }

    /// The parsed `charts` array, mirroring [`Self::kpis`].
    #[must_use]
    pub fn charts(&self) -> &[ChartSpec] {
        &self.charts
    }
}

fn load_builtin_dashboard_spec() -> BuiltinDashboardSpecFile {
    let Ok(path) = std::env::var("BUILTIN_DASHBOARD_SPEC").map(|v| v.trim().to_owned()) else {
        tracing::info!("BUILTIN_DASHBOARD_SPEC not set; built-in dashboard tiles disabled");
        return BuiltinDashboardSpecFile::default();
    };
    if path.is_empty() {
        tracing::info!("BUILTIN_DASHBOARD_SPEC is empty; built-in dashboard tiles disabled");
        return BuiltinDashboardSpecFile::default();
    }
    let raw = match std::fs::read_to_string(&path) {
        Ok(raw) => raw,
        Err(err) => {
            tracing::error!(
                %err,
                path,
                "BUILTIN_DASHBOARD_SPEC could not be read; built-in dashboard tiles disabled"
            );
            return BuiltinDashboardSpecFile::default();
        }
    };
    match parse_builtin_dashboard_spec(&raw) {
        Ok(spec) => spec,
        Err(err) => {
            tracing::error!(
                %err,
                path,
                "BUILTIN_DASHBOARD_SPEC is not valid JSON; built-in dashboard tiles disabled"
            );
            BuiltinDashboardSpecFile::default()
        }
    }
}

static BUILTIN_SPEC: LazyLock<BuiltinDashboardSpecFile> =
    LazyLock::new(load_builtin_dashboard_spec);

/// Built-in KPI tiles for this tenant, from `BUILTIN_DASHBOARD_SPEC`. Empty
/// when the env var is unset, unreadable, or invalid — this replaces the
/// retired `BUILTIN_DASHBOARD_ENABLED` flag (empty = off).
pub static KPIS: LazyLock<Vec<KpiSpec>> = LazyLock::new(|| BUILTIN_SPEC.kpis().to_vec());

/// Built-in chart tiles for this tenant, mirroring [`KPIS`].
pub static CHARTS: LazyLock<Vec<ChartSpec>> = LazyLock::new(|| BUILTIN_SPEC.charts().to_vec());

/// The built-in charts, for cross-language drift guards (compare against the
/// captured parity corpus).
#[must_use]
pub fn charts() -> &'static [ChartSpec] {
    &CHARTS
}

/// The built-in KPIs, mirroring [`charts`].
#[must_use]
pub fn kpis() -> &'static [KpiSpec] {
    &KPIS
}

/// Look up the SQL for a built-in id (KPI or chart).
///
/// Returns `None` if `id` does not match a built-in KPI or chart.
#[must_use]
pub fn spec_sql(id: &str) -> Option<String> {
    KPIS.iter()
        .find(|k| k.id == id)
        .map(|k| k.sql.clone())
        .or_else(|| CHARTS.iter().find(|c| c.id == id).map(|c| c.sql.clone()))
}

/// Render-facing view of a [`ChartSpec`]: everything except `sql`, plus the
/// resolved [`ChartSource`]. This is what gets sent to the browser.
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct ChartRenderSpec {
    /// Stable identifier.
    pub id: String,
    /// Display title.
    pub title: String,
    /// Optional subtitle.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subtitle: Option<String>,
    /// How to render the data.
    pub kind: ChartKind,
    /// Source mart — for lineage/labeling.
    pub mart: String,
    /// Column name for the X axis / category.
    pub x: String,
    /// Column name(s) for the Y axis / measure(s).
    pub y: ChartY,
    /// Optional 2nd-dimension breakdown column.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub series: Option<String>,
    /// Numeric display format.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub format: Option<NumFmt>,
    /// Grid span; `2` = full width.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub span: Option<u8>,
    /// Markdown content for `kind: "text"` tiles.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    /// Caption/unit for `kind: "kpi"` tiles.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub caption: Option<String>,
    /// Target/max value for `kind: "gauge"` tiles.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub target: Option<f64>,
    /// Where this spec originated.
    pub source: ChartSource,
    /// Owning board id, when applicable.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub board: Option<String>,
    /// Structured definition (`ChartInput`), for prefill when editing.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub def: Option<serde_json::Value>,
}

/// Strip `sql` from `spec`, attach its origin — for API responses sent to
/// the browser. Ports `toRenderSpec` in `dashboard-specs.ts`.
#[must_use]
pub fn to_render_spec(spec: &ChartSpec, source: ChartSource) -> ChartRenderSpec {
    ChartRenderSpec {
        id: spec.id.clone(),
        title: spec.title.clone(),
        subtitle: spec.subtitle.clone(),
        kind: spec.kind,
        mart: spec.mart.clone(),
        x: spec.x.clone(),
        y: spec.y.clone(),
        series: spec.series.clone(),
        format: spec.format,
        span: spec.span,
        text: spec.text.clone(),
        caption: spec.caption.clone(),
        target: spec.target,
        source,
        board: None,
        def: None,
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]

    use super::*;

    #[test]
    fn chart_kind_serializes_lowercase() {
        assert_eq!(serde_json::to_string(&ChartKind::Hbar).unwrap(), "\"hbar\"");
        assert_eq!(serde_json::to_string(&ChartKind::Kpi).unwrap(), "\"kpi\"");
    }

    #[test]
    fn chart_source_serializes_lowercase() {
        assert_eq!(
            serde_json::to_string(&ChartSource::Builtin).unwrap(),
            "\"builtin\""
        );
    }

    // `charts()`/`kpis()`/`spec_sql()` all read the process-wide
    // `KPIS`/`CHARTS` statics, which are empty unless `BUILTIN_DASHBOARD_SPEC`
    // is set (Task 6) — setting that env var from within one test would race
    // every other test in this binary that touches the same `LazyLock`, so
    // the tests below either build a `ChartSpec`/`KpiSpec` directly (now
    // straightforward: the fields are owned `String`) or parse the shipped
    // fixture file through the pure [`parse_builtin_dashboard_spec`], never
    // the statics.

    impl ChartY {
        fn single(value: &str) -> Self {
            Self::Single(value.to_owned())
        }

        fn multi(values: &[&str]) -> Self {
            Self::Multi(values.iter().map(|v| (*v).to_owned()).collect())
        }
    }

    fn sample_chart(id: &str, y: ChartY) -> ChartSpec {
        ChartSpec {
            id: id.to_owned(),
            title: "Title".to_owned(),
            subtitle: None,
            kind: ChartKind::Bar,
            mart: "mart_wisman".to_owned(),
            sql: "SELECT 1".to_owned(),
            x: "x".to_owned(),
            y,
            series: None,
            format: Some(NumFmt::Int),
            span: None,
            text: None,
            caption: None,
            target: None,
        }
    }

    #[test]
    fn spec_sql_returns_none_for_an_unknown_id() {
        assert!(spec_sql("does_not_exist").is_none());
    }

    #[test]
    fn to_render_spec_strips_sql_and_sets_source() {
        let spec = sample_chart("wisman_tren", ChartY::single("jumlah"));
        let render = to_render_spec(&spec, ChartSource::Builtin);
        assert_eq!(render.id, spec.id);
        assert_eq!(render.source, ChartSource::Builtin);
        let json = serde_json::to_value(&render).unwrap();
        assert!(json.get("sql").is_none());
    }

    #[test]
    fn stacked_chart_y_is_multi() {
        let dtw = sample_chart("dtw_top", ChartY::multi(&["wisnus", "wisman"]));
        assert_eq!(
            dtw.y,
            ChartY::Multi(vec!["wisnus".to_owned(), "wisman".to_owned()])
        );
    }

    #[test]
    fn parse_builtin_dashboard_spec_reads_kpis_and_charts() {
        let json = r#"{
            "kpis": [
                {"id": "k1", "title": "K1", "mart": "m1", "sql": "SELECT 1 AS v", "format": "int", "caption": null}
            ],
            "charts": [
                {"id": "c1", "title": "C1", "subtitle": null, "kind": "bar", "mart": "m1",
                 "sql": "SELECT 1", "x": "a", "y": "b", "series": null, "format": "int",
                 "span": null, "text": null, "caption": null, "target": null}
            ]
        }"#;
        let spec = parse_builtin_dashboard_spec(json).unwrap();
        assert_eq!(spec.kpis.len(), 1);
        assert_eq!(spec.kpis[0].id, "k1");
        assert_eq!(spec.charts.len(), 1);
        assert_eq!(spec.charts[0].kind, ChartKind::Bar);
    }

    #[test]
    fn parse_builtin_dashboard_spec_defaults_both_arrays_when_absent() {
        let spec = parse_builtin_dashboard_spec("{}").unwrap();
        assert!(spec.kpis.is_empty());
        assert!(spec.charts.is_empty());
    }

    #[test]
    fn parse_builtin_dashboard_spec_rejects_malformed_json() {
        assert!(parse_builtin_dashboard_spec("not json").is_err());
    }

    #[test]
    fn shipped_default_spec_parses_and_matches_the_byte_count_of_the_former_static_catalog() {
        // The shipped default is the exact 4 KPIs + 9 charts this module
        // used to hardcode — this is the regression guard that the JSON
        // migration didn't drop or duplicate an entry.
        let raw = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("specs/builtin-default.json"),
        )
        .unwrap();
        let spec = parse_builtin_dashboard_spec(&raw).unwrap();
        assert_eq!(spec.kpis.len(), 4);
        assert_eq!(spec.charts.len(), 9);
    }
}
