//! Static "metrics as code" chart and KPI definitions.
//!
//! Ports `src/lib/dashboard-specs.ts` — a thin semantic layer for
//! dashboarding: each card is defined once here (its `ClickHouse` SQL, run
//! server-side, plus how to render it), sourced exclusively from the Gold
//! marts under `serving.*` (the only layer dashboards are allowed to read;
//! Raw/Bronze/Silver are off-limits).

use std::sync::LazyLock;

use serde::{Deserialize, Serialize};

/// How a chart's data should be rendered.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ChartKind {
    /// Vertical bar chart.
    Bar,
    /// Horizontal bar chart.
    Hbar,
    /// Line chart.
    Line,
    /// Area chart.
    Area,
    /// Stacked bar/area chart (multiple `y` series).
    Stacked,
    /// Combined bar + line chart.
    Combo,
    /// Pie chart.
    Pie,
    /// Rose (polar area) chart.
    Rose,
    /// Funnel chart.
    Funnel,
    /// Treemap.
    Treemap,
    /// Scatter plot.
    Scatter,
    /// Bubble chart.
    Bubble,
    /// Heatmap.
    Heatmap,
    /// Radar chart.
    Radar,
    /// Waterfall chart.
    Waterfall,
    /// Geographic choropleth map.
    Geomap,
    /// Single-number KPI tile.
    Kpi,
    /// Single-number gauge tile.
    Gauge,
    /// Raw data table.
    Table,
    /// Free-text markdown tile (no SQL).
    Text,
}

/// Numeric display format for a chart or KPI value.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum NumFmt {
    /// Integer display.
    Int,
    /// Floating-point display.
    Float,
}

/// Aggregate function applied to a chart's measure column(s). Ports the TS
/// `AGGS` set (`bi-store.ts:53`: `sum`/`avg`/`max`/`min`/`count`).
///
/// [`crate::store`]'s module doc claims there is no SQL injection path
/// because chart SQL is assembled only from validated identifiers — but
/// before this type existed, `QueryBuilder::aggregate` took `impl
/// Into<String>` and interpolated it raw into the generated SQL. On the
/// `spec_from_input` path the string was allowlisted first (via
/// `aggregate_allowed`), but on the `sql_with_filters` path it came
/// straight from a stored `spec_json`'s `def.aggregate` and was NEVER
/// re-checked — reachable only by whoever already has direct write access
/// to `console.bi_chart` (not via any HTTP route), but it meant the doc
/// claim wasn't true by construction. This enum makes it true: the only
/// way to get an `Aggregate` out of untrusted text is
/// [`Aggregate::from_str_lossy`], which can only ever produce one of the
/// five known variants — an unrecognized string can never reach the SQL
/// builder as raw text.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Aggregate {
    /// `sum(...)` — also the default when unset or unrecognized.
    #[default]
    Sum,
    /// `avg(...)`.
    Avg,
    /// `max(...)`.
    Max,
    /// `min(...)`.
    Min,
    /// `count()`.
    Count,
}

impl Aggregate {
    /// The lowercase `ClickHouse` function name this aggregate renders as
    /// (`count` renders as `count()`, callers handle that specially).
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Sum => "sum",
            Self::Avg => "avg",
            Self::Max => "max",
            Self::Min => "min",
            Self::Count => "count",
        }
    }

    /// Parse a stored aggregate string, falling back to [`Aggregate::Sum`]
    /// for anything unrecognized (case-insensitively) — matching the TS
    /// `d.aggregate ?? "sum"` default (`bi-store.ts:394`) and, per the
    /// data-loss lesson of B1, extended to cover a genuinely corrupt/unknown
    /// value too: this must NEVER error, since `sql_with_filters` runs
    /// against already-stored rows and an error here would either panic or
    /// have to fall back to dropping the chart, both worse than silently
    /// defaulting to `sum` (the TS's own behavior for a missing aggregate).
    #[must_use]
    pub fn from_str_lossy(s: &str) -> Self {
        match s.to_ascii_lowercase().as_str() {
            "avg" => Self::Avg,
            "max" => Self::Max,
            "min" => Self::Min,
            "count" => Self::Count,
            _ => Self::Sum,
        }
    }
}

impl std::fmt::Display for Aggregate {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Where a chart spec originated: bundled with the app, generated by the AI
/// chat tool, or created manually through the dashboard builder UI.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ChartSource {
    /// Bundled with the app (this module's `KPIS`/`CHARTS` constants).
    Builtin,
    /// Generated by the AI chat tool.
    Ai,
    /// Created manually through the dashboard builder UI.
    Ui,
}

/// A single-number KPI. The `sql` must return a column named `v` (and may
/// return other columns too).
#[derive(Debug, Clone, PartialEq)]
pub struct KpiSpec {
    /// Stable identifier.
    pub id: &'static str,
    /// Display title.
    pub title: &'static str,
    /// `ClickHouse` SQL that returns a `v` column.
    pub sql: &'static str,
    /// Numeric display format.
    pub format: NumFmt,
    /// Optional caption/unit shown under the value.
    pub caption: Option<&'static str>,
    /// Source mart — for lineage/labeling.
    pub mart: &'static str,
}

/// A chart's `y` axis: a single measure column, or several for a stacked
/// chart.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ChartY {
    /// A single measure column.
    Single(String),
    /// Multiple measure columns (used by `kind: "stacked"`).
    Multi(Vec<String>),
}

/// A chart. `sql` returns rows; `x`/`y` name the columns used for the
/// axis/series.
#[derive(Debug, Clone, PartialEq)]
pub struct ChartSpec {
    /// Stable identifier.
    pub id: &'static str,
    /// Display title.
    pub title: &'static str,
    /// Optional subtitle.
    pub subtitle: Option<&'static str>,
    /// How to render the data.
    pub kind: ChartKind,
    /// Source mart — for lineage/labeling.
    pub mart: &'static str,
    /// `ClickHouse` SQL that returns the chart's rows.
    pub sql: &'static str,
    /// Column name for the X axis / category.
    pub x: &'static str,
    /// Column name(s) for the Y axis / measure(s).
    pub y: ChartY,
    /// Optional 2nd-dimension breakdown column: splits `y` into multiple
    /// series by this column's value. When set, `y` is a single measure and
    /// the data is long-format (x, series, value).
    pub series: Option<&'static str>,
    /// Numeric display format.
    pub format: Option<NumFmt>,
    /// Grid span; `2` = full width.
    pub span: Option<u8>,
    /// Markdown content for `kind: "text"` tiles (no SQL).
    pub text: Option<&'static str>,
    /// Caption/unit for `kind: "kpi"` tiles.
    pub caption: Option<&'static str>,
    /// Target/max value for `kind: "gauge"` tiles (auto from data when
    /// unset).
    pub target: Option<f64>,
}

impl ChartY {
    fn single(value: &'static str) -> Self {
        Self::Single(value.to_owned())
    }

    fn multi(values: &[&'static str]) -> Self {
        Self::Multi(values.iter().map(|v| (*v).to_owned()).collect())
    }
}

/// Built-in KPI tiles, ported verbatim from `KPIS` in `dashboard-specs.ts`.
pub static KPIS: LazyLock<Vec<KpiSpec>> = LazyLock::new(|| {
    vec![
        KpiSpec {
            id: "kpi_wisman_total",
            title: "Total Foreign Visitors",
            mart: "mart_wisman",
            sql: "SELECT sum(jumlah) AS v FROM serving.mart_wisman",
            format: NumFmt::Int,
            caption: Some("foreign visits (cumulative)"),
        },
        KpiSpec {
            id: "kpi_dtw",
            title: "Tracked Destinations",
            mart: "mart_kunjungan_dtw",
            sql: "SELECT count(DISTINCT destinasi) AS v FROM serving.mart_kunjungan_dtw",
            format: NumFmt::Int,
            caption: Some("tourist attractions (DTW)"),
        },
        KpiSpec {
            id: "kpi_event",
            title: "Events (Latest Year)",
            mart: "mart_event",
            sql: "SELECT jumlah_event AS v, tahun FROM serving.mart_event ORDER BY tahun DESC LIMIT 1",
            format: NumFmt::Int,
            caption: Some("number of events in the latest year"),
        },
        KpiSpec {
            id: "kpi_gci",
            title: "GCI Indicators Ready",
            mart: "mart_gci_readiness",
            sql: "SELECT sum(data_tersedia) AS v, count() AS total FROM serving.mart_gci_readiness",
            format: NumFmt::Int,
            caption: Some("indicators with data available"),
        },
    ]
});

/// Built-in chart tiles, ported verbatim from `CHARTS` in
/// `dashboard-specs.ts`. The TS builds each `sql` from a `const S =
/// "serving"` template; here the `serving.` prefix is inlined directly into
/// each `&'static str` literal, byte-identical to the interpolated result.
pub static CHARTS: LazyLock<Vec<ChartSpec>> = LazyLock::new(|| {
    vec![
        ChartSpec {
            id: "wisman_tren",
            title: "Foreign Visitor Trend",
            subtitle: Some("Monthly total across years"),
            kind: ChartKind::Area,
            mart: "mart_wisman",
            span: Some(2),
            sql: "SELECT concat(toString(tahun),'-',leftPad(toString(bulan_no),2,'0')) AS periode,\n                 round(sum(jumlah)) AS jumlah\n          FROM serving.mart_wisman\n          GROUP BY tahun, bulan_no\n          ORDER BY tahun, bulan_no",
            x: "periode",
            y: ChartY::single("jumlah"),
            series: None,
            format: Some(NumFmt::Int),
            text: None,
            caption: None,
            target: None,
        },
        ChartSpec {
            id: "wisman_negara",
            title: "Top Source Countries",
            subtitle: Some("Top 10 nationalities"),
            kind: ChartKind::Hbar,
            mart: "mart_wisman",
            span: None,
            sql: "SELECT negara, round(sum(jumlah)) AS jumlah\n          FROM serving.mart_wisman\n          GROUP BY negara ORDER BY jumlah DESC LIMIT 10",
            x: "negara",
            y: ChartY::single("jumlah"),
            series: None,
            format: Some(NumFmt::Int),
            text: None,
            caption: None,
            target: None,
        },
        ChartSpec {
            id: "wisman_kawasan",
            title: "Visitors by Region",
            subtitle: Some("Distribution by continent/region"),
            kind: ChartKind::Pie,
            mart: "mart_wisman",
            span: None,
            sql: "SELECT kawasan, round(sum(jumlah)) AS jumlah\n          FROM serving.mart_wisman\n          GROUP BY kawasan ORDER BY jumlah DESC",
            x: "kawasan",
            y: ChartY::single("jumlah"),
            series: None,
            format: Some(NumFmt::Int),
            text: None,
            caption: None,
            target: None,
        },
        ChartSpec {
            id: "wisman_pintu",
            title: "Visitors by Entry Point",
            subtitle: Some("Arrival points"),
            kind: ChartKind::Bar,
            mart: "mart_wisman",
            span: None,
            sql: "SELECT pintu_masuk, round(sum(jumlah)) AS jumlah\n          FROM serving.mart_wisman\n          GROUP BY pintu_masuk ORDER BY jumlah DESC",
            x: "pintu_masuk",
            y: ChartY::single("jumlah"),
            series: None,
            format: Some(NumFmt::Int),
            text: None,
            caption: None,
            target: None,
        },
        ChartSpec {
            id: "dtw_top",
            title: "Visits by Destination",
            subtitle: Some("Domestic vs foreign, top 8 destinations"),
            kind: ChartKind::Stacked,
            mart: "mart_kunjungan_dtw",
            span: Some(2),
            sql: "SELECT destinasi, round(sum(wisnus)) AS wisnus, round(sum(wisman)) AS wisman\n          FROM serving.mart_kunjungan_dtw\n          GROUP BY destinasi ORDER BY sum(total) DESC LIMIT 8",
            x: "destinasi",
            y: ChartY::multi(&["wisnus", "wisman"]),
            series: None,
            format: Some(NumFmt::Int),
            text: None,
            caption: None,
            target: None,
        },
        ChartSpec {
            id: "event_tren",
            title: "Event Count Trend",
            subtitle: Some("Per year"),
            kind: ChartKind::Line,
            mart: "mart_event",
            span: None,
            sql: "SELECT toString(tahun) AS tahun, jumlah_event AS jumlah\n          FROM serving.mart_event ORDER BY tahun",
            x: "tahun",
            y: ChartY::single("jumlah"),
            series: None,
            format: Some(NumFmt::Int),
            text: None,
            caption: None,
            target: None,
        },
        ChartSpec {
            id: "gci_readiness",
            title: "GCI Data Readiness",
            subtitle: Some("Readiness status distribution"),
            kind: ChartKind::Pie,
            mart: "mart_gci_readiness",
            span: None,
            sql: "SELECT readiness, count() AS n\n          FROM serving.mart_gci_readiness\n          GROUP BY readiness ORDER BY n DESC",
            x: "readiness",
            y: ChartY::single("n"),
            series: None,
            format: Some(NumFmt::Int),
            text: None,
            caption: None,
            target: None,
        },
        ChartSpec {
            id: "kuliner_wilayah",
            title: "Culinary Businesses by Area",
            subtitle: Some("Registered businesses"),
            kind: ChartKind::Bar,
            mart: "mart_kuliner",
            span: None,
            sql: "SELECT wilayah, sum(jumlah_usaha) AS jumlah\n          FROM serving.mart_kuliner\n          GROUP BY wilayah ORDER BY jumlah DESC",
            x: "wilayah",
            y: ChartY::single("jumlah"),
            series: None,
            format: Some(NumFmt::Int),
            text: None,
            caption: None,
            target: None,
        },
        ChartSpec {
            id: "atlas_poi",
            title: "Tourism POIs by Category",
            subtitle: Some("Number of POIs"),
            kind: ChartKind::Hbar,
            mart: "mart_atlas",
            span: None,
            sql: "SELECT kategori, jumlah_poi AS jumlah\n          FROM serving.mart_atlas ORDER BY jumlah_poi DESC",
            x: "kategori",
            y: ChartY::single("jumlah"),
            series: None,
            format: Some(NumFmt::Int),
            text: None,
            caption: None,
            target: None,
        },
    ]
});

/// The built-in charts, for cross-language drift guards (compare against the
/// captured parity corpus).
#[must_use]
pub fn charts() -> &'static [ChartSpec] {
    &CHARTS
}

/// The built-in KPIs, mirroring [`charts`].
#[must_use]
pub fn kpis() -> &'static [KpiSpec] {
    &KPIS
}

/// Look up the SQL for a built-in id (KPI or chart), mirroring the TS
/// `SPEC_SQL` map (`Object.fromEntries([...KPIS, ...CHARTS].map(...))`).
///
/// Returns `None` if `id` does not match a built-in KPI or chart.
#[must_use]
pub fn spec_sql(id: &str) -> Option<&'static str> {
    KPIS.iter()
        .find(|k| k.id == id)
        .map(|k| k.sql)
        .or_else(|| CHARTS.iter().find(|c| c.id == id).map(|c| c.sql))
}

/// Render-facing view of a [`ChartSpec`]: everything except `sql`, plus the
/// resolved [`ChartSource`]. This is what gets sent to the browser.
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct ChartRenderSpec {
    /// Stable identifier.
    pub id: String,
    /// Display title.
    pub title: String,
    /// Optional subtitle.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subtitle: Option<String>,
    /// How to render the data.
    pub kind: ChartKind,
    /// Source mart — for lineage/labeling.
    pub mart: String,
    /// Column name for the X axis / category.
    pub x: String,
    /// Column name(s) for the Y axis / measure(s).
    pub y: ChartY,
    /// Optional 2nd-dimension breakdown column.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub series: Option<String>,
    /// Numeric display format.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub format: Option<NumFmt>,
    /// Grid span; `2` = full width.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub span: Option<u8>,
    /// Markdown content for `kind: "text"` tiles.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    /// Caption/unit for `kind: "kpi"` tiles.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub caption: Option<String>,
    /// Target/max value for `kind: "gauge"` tiles.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub target: Option<f64>,
    /// Where this spec originated.
    pub source: ChartSource,
    /// Owning board id, when applicable.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub board: Option<String>,
    /// Structured definition (`ChartInput`), for prefill when editing.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub def: Option<serde_json::Value>,
}

/// Strip `sql` from `spec`, attach its origin — for API responses sent to
/// the browser. Ports `toRenderSpec` in `dashboard-specs.ts`.
#[must_use]
pub fn to_render_spec(spec: &ChartSpec, source: ChartSource) -> ChartRenderSpec {
    ChartRenderSpec {
        id: spec.id.to_owned(),
        title: spec.title.to_owned(),
        subtitle: spec.subtitle.map(str::to_owned),
        kind: spec.kind,
        mart: spec.mart.to_owned(),
        x: spec.x.to_owned(),
        y: spec.y.clone(),
        series: spec.series.map(str::to_owned),
        format: spec.format,
        span: spec.span,
        text: spec.text.map(str::to_owned),
        caption: spec.caption.map(str::to_owned),
        target: spec.target,
        source,
        board: None,
        def: None,
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]

    use super::*;

    #[test]
    fn chart_kind_serializes_lowercase() {
        assert_eq!(serde_json::to_string(&ChartKind::Hbar).unwrap(), "\"hbar\"");
        assert_eq!(serde_json::to_string(&ChartKind::Kpi).unwrap(), "\"kpi\"");
    }

    #[test]
    fn chart_source_serializes_lowercase() {
        assert_eq!(
            serde_json::to_string(&ChartSource::Builtin).unwrap(),
            "\"builtin\""
        );
    }

    #[test]
    fn charts_has_nine_entries() {
        assert_eq!(charts().len(), 9);
    }

    #[test]
    fn kpis_has_four_entries() {
        assert_eq!(kpis().len(), 4);
    }

    #[test]
    fn spec_sql_finds_kpi_and_chart() {
        assert!(spec_sql("kpi_wisman_total").is_some());
        assert!(spec_sql("wisman_tren").is_some());
        assert!(spec_sql("does_not_exist").is_none());
    }

    #[test]
    fn to_render_spec_strips_sql_and_sets_source() {
        let spec = &charts()[0];
        let render = to_render_spec(spec, ChartSource::Builtin);
        assert_eq!(render.id, spec.id);
        assert_eq!(render.source, ChartSource::Builtin);
        let json = serde_json::to_value(&render).unwrap();
        assert!(json.get("sql").is_none());
    }

    #[test]
    fn stacked_chart_y_is_multi() {
        let dtw = charts().iter().find(|c| c.id == "dtw_top").unwrap();
        assert_eq!(
            dtw.y,
            ChartY::Multi(vec!["wisnus".to_owned(), "wisman".to_owned()])
        );
    }
}
